apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/fail2ban1337/abelomar.git
    path: .
    targetRevision: HEAD
  syncPolicy:
    automated: {}