Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  #https://stackoverflow.com/questions/37556968/vagrant-disable-guest-additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  #https://stackoverflow.com/questions/18528717/vagrant-shared-and-synced-folders
  config.vm.synced_folder "./confs", "/vagrant"
  config.vm.provision :shell, path: "./scripts/server.sh"
  config.vm.provision "shell", inline: "/usr/local/bin/kubectl apply -f /vagrant/."
  config.vm.define "abelomarS" do |control|
    control.vm.provider "virtualbox" do |v|
      control.vm.hostname = "abelomarS"
      control.vm.network "private_network", ip: "192.168.42.110"
      v.cpus = 1
      v.memory = 1024
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
  end
end