kind: Deployment
apiVersion: apps/v1
metadata:
  name: app2-app
  labels:
    app: app2-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-app
  template:
    metadata:
      labels:
        app: app2-app
    spec:
      containers:
      - name: app2-app
        image: nginx:1.14.2
        # image: paulbouwer/hello-kubernetes:1.10
        # args:
        # - "-text=App 1"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: app2-html

---
kind: Service
apiVersion: v1
metadata:
  name: app2-service
spec:
  selector:
    app: app2-app
  ports:
  - port: 80

---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app2-ingress
spec:
  rules:
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2-service
            port:
              number: 80

